name: note_app
description: A new Flutter project.
publish_to: 'none'
# version: 0.1.0
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  equatable: ^2.0.3
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  get_it: ^7.2.0
  intl: ^0.18.1
  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.3
  flip_card: ^0.7.0
  font_awesome_flutter: ^10.4.0
  awesome_dialog: ^3.1.0
  syncfusion_flutter_charts: 21.2.5
  pie_chart: ^5.3.2
  swipeable_card_stack:
    git:
      url: https://github.com/wgrzesik/cta-flutter-tinder-card-animation.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Montserrat
    fonts:
      - asset: Montserrat-VariableFont_wght.ttf

